### ISSUE TITLE
Rollback/delete IAM Role if Lambda creation fails

### ISSUE THREAD

**Issue by dreamorosi** [aws-samples/aws-efs-simple-file-manager#126]
While onboarding an unmanaged EFS volume that I just created I got an error because I forgot to create a mount target for it. 
After fixing the issue I went back and ran the onboarding again but this time I got an `EntityAlreadyExists` error because the IAM Role was leftover from the previous execution.

This happens, I think, because the `create_function_role` function is called inside the `create_function` function, see [here](https://github.com/aws-samples/aws-efs-simple-file-manager/blob/02702d8ad4fba036cec313d6d8d3fa0f800adfd9/source/api/app.py#L234), but in the `except` block of the `create_function` function invocation we are deleting only the access point, not the IAM Role, see [here](https://github.com/aws-samples/aws-efs-simple-file-manager/blob/02702d8ad4fba036cec313d6d8d3fa0f800adfd9/source/api/app.py#L395). 

I'd recommend trying to delete the IAM Role just created if the onboarding operation fails, if you agree I'm happy to open a PR.

**Comment by brandold** [comment]
Feel free to open a PR for this if you'd like. Otherwise we'll get it in our sprint backlog. Thanks for reporting!
