### ISSUE TITLE
FileSystem page rebuilt so users can easily mount new EFS filesystems. 

### ISSUE THREAD

**Issue by eggoynes** [aws-samples/aws-efs-simple-file-manager#22]

**Comment by brandold** [comment]
Per Will on this topic: 

"it’s not a “mount point”, it’s “mount target”, and there shouldn’t be any need to select a one. You can simplify this in one of two ways:
Just pick one at random (simple, not super high available). Make sure you restrict the lambda to the same subnet.
Get list of subnets from all mount targets, use all of them with the Lambda."

**Comment by brandold** [comment]
Further context: "AP config should be configurable (replace mount target configuration with this).
You should name it something like “SimpleFileManager” so EFS users know where it came from.
Allow users to configure UID/GID/RootDir when they switch a file system to managed.
Default choices should be 1000:1000 /simplefilemanager"

**Comment by eggoynes** [comment]
Tasks 

1) Pass List of networkid to **create_filesystem_lambda**
Change subnet_id from a string to a list. Pass in the whole list of subnets from the web interface. 


2) Add additional configurations when mounting a new file system. 

Permissions
Allow the user to provide a custom mount point inside their EFS filesystem.

**create_filesystem_access_point**
The path /efs stays the same.

LocalMountPath is what the user is able to configure with an input form input. I will provide default values in all of these as well to make it easier for the user. 
https://bootstrap-vue.org/docs/components/form-input

3) Additionally provide these as inputs on the page. 
User ID as input.
Group ID as input.

Default Values can be 1000:1000 
Directory /simplefilemanager
