### ISSUE TITLE
SignUp is not permitted for this user pool

### ISSUE THREAD

**Issue by eggoynes** [aws-samples/aws-efs-simple-file-manager#44]
I tried to make myself a new user. 

But get the error "Sign up not permitted for this userpool"

**Comment by brandold** [comment]
We actually don't want to allow this - at least not at this time. I think there is a vue prop that will disable the sign up option.

**Comment by EddieGoynesAmazon** [comment]
Sounds good. 

1) Let me find the Vue Prop to disable creating new users. 
2) I can see how this could be a security issue if a non admin user created other users for their friends.

**Comment by eggoynes** [comment]
This is closed from this pull request. 
https://github.com/aws-samples/aws-efs-simple-file-manager/pull/48
