### ISSUE TITLE
Show that there are no file systems instead of throwing error Fix. 

### ISSUE THREAD

**Issue by eggoynes** [aws-samples/aws-efs-simple-file-manager#46]
Unable to list filesystems, check api logs.

- The page should show this message in the page. And make it more user-friendly such as. 
```You currently do not have any EFS file systems. ```

![image](https://user-images.githubusercontent.com/40248820/114611884-57421080-9c56-11eb-8b5a-a67729ab5204.png)

**Comment by EddieGoynesAmazon** [comment]
Have a Vue If Else Statement to change this page if a user does not have any EFS filesystems on their AWS Account. 
Even have a link generated so it takes them right to their Create EFS Filesystem page. 


![image](https://user-images.githubusercontent.com/40248820/114784983-d7d53f80-9d30-11eb-9f98-c3600c97056e.png)
