### ISSUE TITLE
FS lambda fails to launch due to SG constraint

### ISSUE THREAD

**Issue by wochanda** [aws-samples/aws-efs-simple-file-manager#75]
When attempting to manage a file system with multiple SGs applied to the mount targets the Lambda function creation fails due to this error (SG-ids obfuscated):
api - ERROR - An error occurred (ValidationException) when calling the CreateFunction operation: 1 validation error detected: Value '[sg-1, sg-2, sg-1, sg-2, sg-1, sg-2, sg-1, sg-2, sg-1, sg-2]' at 'vpcConfig.securityGroupIds' failed to satisfy constraint: Member must have length less than or equal to 5

The underlying file system has 5 mount targets, each with the same 2 SGs applied. Presumably SFM is listing security groups for all mount targets and concatenating and applying to the Lambda its launching without first deduping the list.

A secondary issue happens after this when SFM tries to delete the access point it just created:
api - ERROR - An error occurred (400) when calling the DeleteAccessPoint operation:

**Comment by brandold** [comment]
What version of SFM are you running? v1.1.0 or v1.0.0. I thought I had fixed the first issue in the recent release (and the secondary issue is being addressed in this coming release on Tuesday).

**Comment by wochanda** [comment]
Issue is still occurring in v1.1.0 @brandold
