### ISSUE TITLE
Protect against arbitrary malicious content put into application files on Cloudfront

### ISSUE THREAD

**Issue by eggoynes** [aws-samples/aws-efs-simple-file-manager#80]
Can I solve this by just allowing GET requests from Amazon CloudFront for the application files hosted on Amazon S3?
 
 
 Subresource integrity is used to verify hash of application files

**Comment by brandold** [comment]
This has been done before with MIE, if you want to just check out what was done there:

https://github.com/awslabs/aws-media-insights/blob/master/vue.config.js#L1
